NYCPlanning/ae-cp-map

kubb.config.ts
package-lock.json
package.json

Update kubb
Refactor away from deprecated functions
Point to zoning-api as OpenAPI source
closes #19

Update and configure kubb

---

.github/workflows/staging.yml

deploy to heroku

---

app/components/atlas.client.tsx
package-lock.json
package.json

- Map state lat/long and zoom are constrained such that user can't pan away from NYC area. [See this](https://github.com/NYCPlanning/ae-zoning-map-poc/blob/main/src/App.tsx#L262) onViewStateChange from ae-zoning-map-poc for min/max lat/lon and zoom.
- User cannot adjust pitch. It should be constrained to 0 regardless of user input.
Completes #32

32 Constrain map to min/max lat and long for NYC

---

.eslintrc.cjs
app/components/AdminDropdown/BoroughDropdown.test.tsx
app/components/AdminDropdown/CityCouncilDistrictDropdown.test.tsx
app/components/AdminDropdown/CommunityDistrictDropdown.test.tsx
app/components/AdminDropdown/DistrictTypeDropdown.test.tsx
app/components/AdminDropdown/index.test.tsx
app/components/CapitalProjectDetailPanel/CapitalProjectDetailPanel.test.tsx
app/components/CapitalProjectDetailPanel/index.ts
app/components/Overlay.tsx
app/components/layers/useCityCouncilDistrictsLayer.client.tsx
app/components/layers/useCommunityDistrictsLayer.client.tsx
app/gen/axios/findCapitalCommitmentsByManagingCodeCapitalProjectId.ts
app/gen/mocks/createCapitalCommitment.ts
app/gen/types/CapitalCommitment.ts
app/gen/zod/capitalCommitmentSchema.ts
kubb.config.ts
package-lock.json
setup-test.ts

Add ignorePattern in eslint config to skip the app/gen directory
Closes #21

Ignore Kubb files in linter

---

app/components/FilterMenu.tsx
app/components/GoToDistrictBtn/GoToCityCouncilDistrictBtn.test.tsx
app/components/GoToDistrictBtn/GoToCityCouncilDistrictBtn.tsx
app/components/GoToDistrictBtn/GoToCommunityDistrictBtn.test.tsx
app/components/GoToDistrictBtn/GoToCommunityDistrictBtn.tsx
app/components/GoToDistrictBtn/index.test.tsx
app/components/GoToDistrictBtn/index.tsx
app/root.tsx
app/routes/city-council-districts.$cityCouncilDistrictId.capital-projects.tsx

Implement a go to selected geo button
Navigate to capital projects of city council or community district
closes #67

Implement go to selected geo button

---

app/components/CapitalProjectDetailPanel/CapitalProjectDetailPanel.tsx
app/components/CapitalProjectsList/CapitalProjectsAccordionPanel.test.tsx
app/components/CapitalProjectsList/CapitalProjectsAccordionPanel.tsx
app/components/CapitalProjectsList/CapitalProjectsDrawer.test.tsx
app/components/CapitalProjectsList/CapitalProjectsDrawer.tsx
app/components/CapitalProjectsList/CapitalProjectsList.test.tsx
app/components/CapitalProjectsList/CapitalProjectsList.tsx
app/components/CapitalProjectsList/CapitalProjectsListItem.test.tsx
app/components/CapitalProjectsList/CapitalProjectsListItem.tsx
app/components/CapitalProjectsList/index.ts
app/components/FilterMenu.tsx
app/components/Pagination.test.tsx
app/components/Pagination.tsx
app/root.tsx
app/routes/city-council-districts.$cityCouncilDistrictId.capital-projects.tsx
app/routes/city-council-districts.$cityCouncilDistrictId.capital-projects_.$managingCode.$capitalProjectId.tsx
app/utils/utils.ts
package-lock.json
package.json

Related to https://github.com/NYCPlanning/ae-cp-map/issues/14

14 filter capital projects by city council districts

---

app/components/CapitalProjectsList/CapitalProjectsPanel.test.tsx
app/components/CapitalProjectsList/CapitalProjectsPanel.tsx
app/components/CapitalProjectsList/index.ts
app/routes/boroughs.$boroughId.community-districts.$communityDistrictId.capital-projects.tsx
app/routes/city-council-districts.$cityCouncilDistrictId.capital-projects.tsx

Implement the panel to show capital projects in a community district
closes #15

Capital Projects in Community District

---

app/routes/capital-projects.$managingCode.$capitalProjectId.tsx

Refactor capital project detail panel to use updated panel component properly
closes #84

Resolve capital project detail panel hiding

---

package-lock.json
package.json

resolves platform specific install issues

add rollup-darwin-x64 as optional

---

app/components/Overlay.tsx

Add padding to top of overlay on mobile
closes #82

Add filter menu top padding

---

app/components/FilterMenu.tsx
app/components/WelcomePanel/WelcomeContent.test.tsx
app/components/WelcomePanel/WelcomeContent.tsx
app/components/WelcomePanel/WelcomeHeader.test.tsx
app/components/WelcomePanel/WelcomeHeader.tsx
app/components/WelcomePanel/WelcomePanel.test.tsx
app/components/WelcomePanel/WelcomePanel.tsx
app/components/WelcomePanel/index.tsx
app/root.tsx
package-lock.json

Desktop: create an accordian welcome panel
Mobile: create a drawer welcome panel
closes #6

Implement welcome panel

---

.gitignore
app/components/AdminDropdown/DistrictTypeDropdown.tsx
app/root.tsx
app/utils/analytics.js
setup-test.ts

Adds Matomo tracking, along with an example of a tracked event.
Completes #38

38 Added matomo

---

app/root.tsx
app/utils/analytics.js

Add Fullstory to CP map 
tracking works (tested in Safari browser as Chrome browsing didn't reflect in FS segment)
~I do have an error I cannot fix as yet; `FullStory namespace conflict. Please set window["_fs_namespace"].`~
The above error shouldn't occur in prod. Only shows up in develop bc of the `useEffect` effect. 
Closes # 59

59 Add Fullstory analytics

---

.github/workflows/production.yml

Configure a workflow to deploy to production on dispatch
closes #94

Deploy to production

---

.github/workflows/production.yml

Add CPDB data url to production workflow
closes #94

CPDB production url

---

app/components/AdminDropdown/index.tsx

Added button to clear individual selects when they have a value selected.
@jessicashanshanhuang please review styling.
Closes #145

145 Add Clear Filter button to existing Selects

---

app/components/AdminDropdown/index.tsx

Wrapped clear icon in a button to fix accessibility issues
Closes #156

Issue 156 Address Button Accessibility Issues

---

.github/workflows/production.yml

Updated URL for production in In the GitHub workflow
Closes #161

Issue 161 Updated URL in GHA for Prod

---

app/components/AdminDropdown/AgencyDropdown.tsx

Deleted sorting done on agencies in `AgencyDropdown.tsx`
Closes #160

Issue 160 Remove Sorting of Agencies Data

---

app/components/AdminDropdown/AgencyDropdown.tsx
app/components/AdminDropdown/BoroughDropdown.tsx
app/components/AdminDropdown/CityCouncilDistrictDropdown.tsx
app/components/AdminDropdown/CommunityDistrictDropdown.tsx
app/components/AdminDropdown/DistrictTypeDropdown.tsx

Removed the tags that were firing whenever a dropdown was changed.

168 Remove Unwanted Analytics Tags

---

app/components/ProjectAmountMenu/index.tsx
app/root.tsx

- used `commitmentTotalInputsAreValid` in the ProjectsAmount component to display error messaging as needed
Closes #177

Issue 177 

---

app/root.tsx
app/routes/capital-projects.tsx

This PR removes references to the `VITE_FEATURE_FLAG_ATTRIBUTE_FILTERS` feature flag to release the functionality to production.

Remove references to additional filters feature flag
