- app/components/atlas.client.tsx
- app/components/layers/index.tsx
- app/components/layers/useCapitalProjectsLayer.client.tsx
- app/routes/capital-projects.$managingCode.$capitalProjectId.tsx
- package-lock.json
- package.json
- sample.env
- tsconfig.json
Add capital projects layer to the map
Enable auto highlighting
Link selection between route and map style
- Highlighting styling is driven primarily by 'auto highlight' feature
- Went beyond scope of ticket to get quick win with feature selection based on url path
- "Glow" is non-trivial and excluded from the ticket
- vite client types are added for typescript hinting
- Testing is not practical at this time
- playwright doesn't easily see into the canvas
- deck testing libraries seem to be primarily for testing  custom layer types
closes #8
> Render capital projects layer

- app/components/FilterMenu.tsx
- app/components/Overlay.tsx
- app/root.tsx
- app/routes/_index.tsx
1. Adds new root `_index` route that renders a `<FilterMenu>` and the `Show Geography filter` button only on mobile. In combination with the `<FilterMenu>` instance in `root.tsx`, this is mean to accomplish the desired behavior where the filter menu is always shown on desktop sizes but is hidden on mobile on non-root routes (so that content panel can be shown).
2. Connected the district type dropdown to store it's state in query param.
This PR is intended to set up just enough of the FilterMenu component to unblock other works, primarily #12 and #13
> Add separate _index page for mobile filtermenu layout and connect district type to query params

- app/components/atlas.client.tsx
- app/components/layers/index.tsx
- app/components/layers/useCommunityDistrictsLayer.client.tsx
When user selects "Community Districts" from District Type dropdown in FilterMenu component, user sees CD outlines and labels on the map.
District boundary styles match [specs in Figma](https://www.figma.com/design/LYHHoPop9l0jpEivk5CFzJ/Capital-Projects-Portal?node-id=670-5575&t=bHnqp3D5d54Ghn2t-0).
Completes #13
> 13 Show Community Districts layer on map

- app/components/atlas.client.tsx
- app/components/layers/index.tsx
- app/components/layers/useCityCouncilDistrictsLayer.client.tsx
- When user selects "City Council Districts" from District Type dropdown in FilterMenu component, user sees CCD outlines and labels on the map
- District boundary styles match [specs in Figma](https://www.figma.com/design/LYHHoPop9l0jpEivk5CFzJ/Capital-Projects-Portal?node-id=670-5575&t=bHnqp3D5d54Ghn2t-0)
Completes #12
> 12 Show Council Districts layer on map

- app/components/atlas.client.tsx
This PR is a small change that adds a custom [getCursor](https://deck.gl/docs/api-reference/core/deck#getcursor) handler to the `<Deck>` instance in `Atlas`. I noticed that with #23, the cursor still showed up as "drag" even when the user was hovering over pickable features. I think this change provides feedback to the user that they can click on projects.
> Add getCursor handler to Atlas to show pointer cursor on pickable features

- app/components/atlas.client.tsx
- package-lock.json
- package.json
- Map has controls that allow the user to adjust zoom and resetting bearing
- Uses new [ZoomWidget](https://deck.gl/docs/api-reference/widgets/zoom-widget) and [CompassWidget](https://deck.gl/docs/api-reference/widgets/compass-widget) classes from Deck.gl. Due to a https://github.com/visgl/deck.gl/issues/8877 in Deck that was recently patched, this Issue requires upgrading Deck dependencies to most recent version 9.0.20. Note that the controls rendered by Deck widgets will look different than those shown in [figma](https://www.figma.com/design/LYHHoPop9l0jpEivk5CFzJ/Capital-Projects-Portal?node-id=337-3772&t=KGRjmeAKGkxSYIRL-0). That is because those designs use the components from react-map-gl. For this Issue, the default styling of the Deck widgets is sufficient.
- Controls should be …
> 33 Add map zoom and bearing controls

- .github/workflows/qa.yml
- package-lock.json
- package.json
Pin engine to Node 20
Ensure that development and release environments all use the same major node version (20)
closes #54
Configure QA deployment
Create an environment for quality assurance.
Feature branches can be manually deployed for review.
closes #50
> Pin to node 20 & Release to QA branch

- README.md
This PR adds some instructions to `README.md` for using the QA deployment workflow.
> Add instructions for deploying to QA to README

- app/components/atlas.client.tsx
- app/components/layers/index.tsx
- app/components/layers/useCapitalProjectsLayer.client.tsx
- app/components/layers/useCityCouncilDistrictLayer.client.tsx
- app/routes/city-council-districts.$cityCouncilDistrictId.capital-projects.tsx
Closes https://github.com/NYCPlanning/ae-cp-map/issues/62
Waiting for the ✅ from https://github.com/NYCPlanning/ae-cp-map/pull/65 to mitigate merge conflicts. Things to note in this PR:
- I pass an empty string to data instead of using the fallback geometry
- I also added the `hasCityCouncilDistrict` boolean to both capital project and ccd layer because I wanted to more explicitly tie the highlighting of the district and the filtered project tiles together in the code
> 62 filter projects on map by ccd

- app/components/Overlay.tsx
- app/root.tsx
Closes #72 
This PR changes the selector for a couple `pointerEvents: "auto"` styles from `*` to `> *`. This fixes a bug where clicking the down chevron icon on `<Select>` components wouldn't work. By making this selector more specific, the various panels rendered on top of the map work as intended without this style applying to things _within_ the panels.
> Update pointerEvents style selector to only apply to direct children

- app/extensions/FlyToGeoJsonExtension.ts
This change updates `FlyToGeoJsonExtension` to set padding responsively based on `window.innerWidth`. The padding values are rough estimates based on the sizes of the various panels we render on top of the map on mobile and desktop screen sizes.
> Add responsive padding to FlyToGeoJsonExtension

- app/components/CapitalProjectsList/CapitalProjectsDrawer.tsx
Closes https://github.com/NYCPlanning/ae-cp-map/issues/90
The number of total projects per district changed so try CCD 9 instead of CCD 22 to test.
> Fix final end of projects page in mobile views

- .github/workflows/qa.yml
- .github/workflows/staging.yml
- app/components/ExportDataModal.test.tsx
- app/components/ExportDataModal.tsx
- app/components/LinkBtn.test.tsx
- app/components/LinkBtn.tsx
- app/components/WelcomePanel/WelcomeContent.tsx
- app/routes/boroughs.$boroughId.community-districts.$communityDistrictId.capital-projects.tsx
- app/routes/city-council-districts.$cityCouncilDistrictId.capital-projects.tsx
- package-lock.json
- package.json
- sample.env
Add Export data button to each district project list Add modal that links to download for selected or all district data
closes #44
**Note**: *includes [changes explained in comment](https://github.com/NYCPlanning/ae-cp-map/issues/44#issuecomment-2334424495) on original ticket*
> Export data for districts

- app/components/AdminDropdown/BoroughDropdown.test.tsx
- app/components/AdminDropdown/BoroughDropdown.tsx
- app/components/AdminDropdown/CityCouncilDistrictDropdown.test.tsx
- app/components/AdminDropdown/CityCouncilDistrictDropdown.tsx
- app/components/AdminDropdown/CommunityDistrictDropdown.test.tsx
- app/components/AdminDropdown/CommunityDistrictDropdown.tsx
- app/components/AdminDropdown/DistrictTypeDropdown.test.tsx
- app/components/AdminDropdown/DistrictTypeDropdown.tsx
- app/components/Pagination.tsx
- app/root.tsx
- app/utils/types.ts
- app/utils/utils.ts
Closes https://github.com/NYCPlanning/ae-cp-map/issues/101
The issue stems from the fact that when we change something in the dropdowns, we don't consider the page query parameter. Or as Tim mentioned, any previous query parameter. 
~~There are two potential solutions:~~
~~Option 1: Commit c245ed9ddca5ca382f2989f0ce8a2a3842f92b0e passes the page number to each dropdown component so it's accounted for when a value is changed.~~
~~Option 2: Commit ab0d209db97ed286503f55afa50f28d4ce88f769 explicitly deletes the previous page param and appends the first page upon every 'go to district'.~~
~~Both methods explicitly have the first page as a query param in the url whereas before we didn't have it at all. I'm partial to the second method because it's shorter and more straightforward.~~
> Project list updates when filter menu changes

- .github/workflows/production.yml
- .github/workflows/qa.yml
- .github/workflows/staging.yml
- app/utils/analytics.js
- app/utils/utils.ts
Two tickets and two commits on one PR to get the Repository back into a cohesive state
- Refactoring the conditional fixes a logical typo and addresses a typecheck error. closes #131
- Manually install heroku cli makes the ci work again. closes #132
> Make valid: 131/typecheck and 132/heroku-cli

- app/components/atlas.client.tsx
- app/extensions/FlyToGeoJsonExtension.ts
@dhochbaum-dcp  This PR builds on the changes in `125/tm-zoom-pan` to hopefully fix this issue in a way that plays nicer with how we're already using Deck. The fix already on that branch helped me realize the bug was because the map also _pans_ toward your cursor when you zoom. We already implement our own min and max zoom in `onViewStateChange`, based on Deck's [documentation](https://deck.gl/docs/developer-guide/interactivity#add-constraints-to-view-state), but we don't account for the latitude and longitude changing when zooming beyond the minimum zoom level. This change is meant to address that, while sticking with managing the min/max zoom ourselves, instead of mixing managed and unmanaged versions. This also means we only have to account for it in one place, so we don't need the …
> Fix panning at max zoom bug with onViewStateChange logic instead of max and min zoom

- app/components/layers/useCapitalProjectBudgetedGeoJsonLayer.client.tsx
Turn off pickability of selected project layer,
letting event bubble to projects layer
closes #136
> Bugfix: overlapped projects are unselectable

- app/components/atlas.client.tsx
- app/extensions/FlyToGeoJsonExtension.ts
Fixed issue where after fully zooming out using the mouse scroller, any more scrolls move the map to the left/down.
The default minZoom for the MapViewState is 0, so the map was attempting to zoom out, only to be manually corrected in the onViewStateChange.  By setting the minZoom to be MIN_ZOOM in the initial state, we override the default and make the zoom stop before the manual correction in onViewStateChange would otherwise kick in.
Closes #125
> 125 Zooming at max zoom pans map

- app/utils/analytics.js
The issue was caused by ad blocking extensions preventing Matomo from loading, causing the analytics function to fail.  This adds a simple check for window._paq to make sure if adblock is preventing Matomo from loading, it doesn't break features.
Closes #152
> 144 Adblock Breaks Features

- app/components/AdminDropdown/index.tsx
- app/components/ProjectAmountMenu/ProjectAmountMenuInput.test.tsx
- app/components/ProjectAmountMenu/ProjectAmountMenuInput.tsx
- app/components/ProjectAmountMenu/index.test.tsx
- app/components/ProjectAmountMenu/index.tsx
- app/components/layers/useCapitalProjectsLayer.client.tsx
- app/root.tsx
- app/routes/boroughs.$boroughId.community-districts.$communityDistrictId.capital-projects.tsx
- app/routes/capital-projects.tsx
- app/routes/city-council-districts.$cityCouncilDistrictId.capital-projects.tsx
- app/utils/types.ts
- app/utils/utils.test.ts
- app/utils/utils.ts
- package-lock.json
- package.json
* https://github.com/NYCPlanning/ae-zoning-api/issues/426
* https://github.com/NYCPlanning/ae-zoning-api/issues/399
Closes #159
> 159 Add Project Amount filter functionality to front end
